### ISSUE TITLE
Footer fixed from Page width fixed

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#397]
Please add support When Page width fixed then also footer can be fixed.

**Comment by Ian-Hitt** [comment]
@Nirjonadda What do you mean? The footer is fixed when Page Style is set to Fixed. There are options in SP > Footer that let you make footer rows force covered. Check to make sure hose are not enabled.

**Comment by Nirjonadda** [comment]
@Ian-Hitt Where the option?

https://image.prntscr.com/image/O6uz4v5FRXW6KSdfEBURxQ.png

**Comment by Nirjonadda** [comment]
@Ian-Hitt OK disabled Force cover copyright row, Force cover extended footer and Force cover footer menu but still are not fixed from Fixed style.

See here: https://image.prntscr.com/image/6sIf3WLZSUueG5CNAQ2SUQ.png
